name: WhatsApp OSINT API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Debug Environment and Files
        run: |
          ls -la postman/
          echo "RAPIDAPI_KEY is set to ${RAPIDAPI_KEY}"
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Run API Tests
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          newman run postman/WhatsAppOSINTCollection.json \
            -e postman/WhatsAppOSINTEnv.json \
            --env-var "apiKey=${RAPIDAPI_KEY}" \
            -r htmlextra \
            --reporter-htmlextra-export newman-report.html
        shell: bash

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: newman-report.html
